import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blockchain Management",
  description: "Generated by create next app", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" mt-[10px] md:mt-5 scroll-smooth"
      >
        <div className={`${inter.variable} antialiased mx-5 lg:mx-10 bg-white relative`}>
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
